### ISSUE TITLE
Design 2 : Design REST APIs for operations on products and shops

### ISSUE THREAD

**Issue by pavan-nw** [pavan-nw/stock-admin#10]
**Description**
Provide detailed design on how REST APIs looks like to perform desired operations on `products` and `shops`

**Design Details Required**

1. Information REST endpoints with URL, request body JSON and HTTP Method.
2. Information on the response returned by the API
3. Information on all error responses returned by the API

Note: JSON template of request, response and error response need to maintain as a standard for upcoming APIs as well.

**Comment by vghatikar** [comment]
Updated the API documentation

https://github.com/pavan-nw/stock-admin/wiki/API-Documentation
